// =====================================================
// BESTIÁRIO - D&D 5e (SRD) em PT-BR
// Cada monstro tem 'categoria' (tipo) para filtragem.
// Aventuras agrupam encontros por seção (AVENTURAS).
// =====================================================
const MONSTROS = [
  // ---------- GOBLINOIDES ----------
  {
    nome: 'Goblin', categoria: 'Goblinoide',
    loot: { ouroFormula: '2d6', tabela: [{ item: null, peso: 55 }, { item: 'Cimitarra gasta', peso: 20, qtd: 1 }, { item: 'Orelha de goblin (troféu)', peso: 15, qtd: 1 }, { item: 'Poção de Cura', peso: 10, qtd: 1 }] },
    tipo: 'Humanoide pequeno (goblinoide), neutro e mau',
    ca: '15 (armadura de couro, escudo)', hp: '7 (2d6)', velocidade: '9m',
    atributos: { for: 8, des: 14, con: 10, int: 10, sab: 8, car: 8 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 9', idiomas: 'Comum, Goblin',
    cr: '1/4', pe: 50,
    tracos: ['Astúcia Nimble: pode usar Disparada ou Esquivar como ação bônus.'],
    acoes: [
      'Cimitarra: +4 para acertar, alcance 1,5m. Dano: 5 (1d6+2) corte.',
      'Arco Curto: +4 para acertar, alcance 24/96m. Dano: 5 (1d6+2) perfurante.',
    ],
  },
  {
    nome: 'Goblin Mestre (Goblin Boss)', categoria: 'Goblinoide',
    loot: { ouroFormula: '4d6+10', itensGarantidos: ['Chave enferrujada (o que abre?)'], tabela: [{ item: null, peso: 40 }, { item: 'Anel de bronze (5 po)', peso: 30, qtd: 1 }, { item: 'Poção de Cura', peso: 20, qtd: 1 }, { item: 'Mapa rabiscado do covil', peso: 10, qtd: 1 }] },
    tipo: 'Humanoide pequeno (goblinoide), neutro e mau',
    ca: '17 (cota de malha, escudo)', hp: '21 (5d6+3)', velocidade: '9m',
    atributos: { for: 10, des: 14, con: 10, int: 10, sab: 8, car: 10 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 9', idiomas: 'Comum, Goblin',
    cr: '1', pe: 200,
    tracos: ['Astúcia Nimble: pode usar Disparada ou Esquivar como ação bônus.'],
    acoes: [
      'Múltiplos Ataques: faz dois ataques corpo a corpo.',
      'Pé de Cabra: +4 para acertar, alcance 1,5m. Dano: 5 (1d8+1) concussão.',
      'Arco Curto: +4 para acertar, alcance 24/96m. Dano: 5 (1d6+2) perfurante.',
    ],
    reacoes: ['Redirecionar Ataque: quando aliado a 1,5m é atingido, troca de lugar com ele e recebe o ataque no lugar.'],
  },
  {
    nome: 'Hobgoblin', categoria: 'Goblinoide',
    loot: { ouroFormula: '2d6+4', tabela: [{ item: null, peso: 50 }, { item: 'Insígnia militar da legião', peso: 20, qtd: 1 }, { item: 'Espada longa bem conservada', peso: 18, qtd: 1 }, { item: 'Ração de campanha', peso: 12, qtd: 2 }] },
    tipo: 'Humanoide médio (goblinoide), leal e mau',
    ca: '18 (cota de malha, escudo)', hp: '11 (2d8+2)', velocidade: '9m',
    atributos: { for: 13, des: 12, con: 12, int: 10, sab: 10, car: 9 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 10', idiomas: 'Comum, Goblin',
    cr: '1/2', pe: 100,
    tracos: ['Vantagem Marcial: 1x/turno, +7 (2d6) de dano a um alvo adjacente a um aliado do hobgoblin.'],
    acoes: [
      'Espada Longa: +3 para acertar, alcance 1,5m. Dano: 6 (1d8+1) corte (1d10+1 com duas mãos).',
      'Arco Longo: +3 para acertar, alcance 45/180m. Dano: 5 (1d8+1) perfurante.',
    ],
  },
  {
    nome: 'Bugbear', categoria: 'Goblinoide',
    loot: { ouroFormula: '3d6+5', tabela: [{ item: null, peso: 50 }, { item: 'Saco de "tesouros" (bugigangas roubadas)', peso: 25, qtd: 1 }, { item: 'Clava de guerra pesada', peso: 15, qtd: 1 }, { item: 'Pedra semipreciosa (10 po)', peso: 10, qtd: 1 }] },
    tipo: 'Humanoide médio (goblinoide), caótico e mau',
    ca: '16 (armadura de couro, escudo)', hp: '27 (5d8+5)', velocidade: '9m',
    atributos: { for: 15, des: 14, con: 13, int: 8, sab: 11, car: 9 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 10', idiomas: 'Comum, Goblin',
    cr: '1', pe: 200,
    tracos: ['Furtividade Brutal: vantagem em Furtividade.', 'Surpresa Selvagem: dano extra (2d6) se acertar uma criatura surpresa.'],
    acoes: [
      'Morning Star: +4 para acertar, alcance 1,5m. Dano: 11 (2d8+2) perfurante.',
      'Lança Arremessada: +4 para acertar, alcance 6/18m. Dano: 9 (2d6+2) perfurante.',
    ],
  },

  // ---------- HUMANOIDES ----------
  {
    nome: 'Bandido', categoria: 'Humanoide',
    loot: { ouroFormula: '2d6+2', tabela: [{ item: null, peso: 50 }, { item: 'Baralho de cartas marcado', peso: 18, qtd: 1 }, { item: 'Frasco de aguardente barata', peso: 17, qtd: 1 }, { item: 'Brinco de prata (5 po)', peso: 15, qtd: 1 }] },
    tipo: 'Humanoide médio (qualquer raça), qualquer alinhamento não-leal',
    ca: '12 (armadura de couro)', hp: '11 (2d8+2)', velocidade: '9m',
    atributos: { for: 11, des: 12, con: 12, int: 10, sab: 10, car: 10 },
    sentidos: 'Percepção Passiva 10', idiomas: 'qualquer um (geralmente Comum)',
    cr: '1/8', pe: 25, tracos: [],
    acoes: [
      'Cimitarra: +3 para acertar, alcance 1,5m. Dano: 4 (1d6+1) corte.',
      'Besta Leve: +3 para acertar, alcance 24/96m. Dano: 5 (1d8+1) perfurante.',
    ],
  },
  {
    nome: 'Capanga (Thug)', categoria: 'Humanoide',
    loot: { ouroFormula: '3d6+5', tabela: [{ item: null, peso: 50 }, { item: 'Soqueira de ferro', peso: 20, qtd: 1 }, { item: 'Lista de nomes riscados', peso: 15, qtd: 1 }, { item: 'Dente de ouro (10 po)', peso: 15, qtd: 1 }] },
    tipo: 'Humanoide médio (qualquer raça), qualquer alinhamento não-bom',
    ca: '11 (armadura de couro)', hp: '32 (5d8+10)', velocidade: '9m',
    atributos: { for: 15, des: 11, con: 14, int: 10, sab: 10, car: 11 },
    sentidos: 'Percepção Passiva 10', idiomas: 'qualquer um (geralmente Comum)',
    cr: '1/2', pe: 100,
    tracos: ['Táticas de Matilha: vantagem em ataques se um aliado estiver a 1,5m do alvo.'],
    acoes: [
      'Múltiplos Ataques: faz dois ataques corpo a corpo.',
      'Maça: +4 para acertar, alcance 1,5m. Dano: 5 (1d6+2) concussão.',
      'Besta Pesada: +2 para acertar, alcance 30/120m. Dano: 5 (1d10) perfurante.',
    ],
  },
  {
    nome: 'Bandido Capitão', categoria: 'Humanoide',
    loot: { ouroFormula: '4d6+15', itensGarantidos: ['Cimitarra de boa forja'], tabela: [{ item: null, peso: 35 }, { item: 'Anel de sinete roubado (25 po)', peso: 25, qtd: 1 }, { item: 'Poção de Cura', peso: 20, qtd: 1 }, { item: 'Carta de um contratante misterioso', peso: 20, qtd: 1 }] },
    tipo: 'Humanoide médio (qualquer raça), qualquer alinhamento não-leal',
    ca: '15 (armadura de couro batido)', hp: '65 (10d8+20)', velocidade: '9m',
    atributos: { for: 15, des: 16, con: 14, int: 14, sab: 11, car: 14 },
    sentidos: 'Percepção Passiva 10', idiomas: 'qualquer dois idiomas',
    cr: '2', pe: 450,
    tracos: [],
    acoes: [
      'Múltiplos Ataques: dois ataques com cimitarra e um com adaga.',
      'Cimitarra: +5 para acertar, alcance 1,5m. Dano: 6 (1d6+3) corte.',
      'Adaga: +5 para acertar, alcance 1,5m/6m. Dano: 5 (1d4+3) perfurante.',
    ],
    reacoes: ['Aparar: +2 na CA contra um ataque corpo a corpo que o acertaria (precisa ver o atacante e empunhar arma corpo a corpo).'],
  },
  {
    nome: 'Guarda', categoria: 'Humanoide',
    tipo: 'Humanoide médio (qualquer raça), qualquer alinhamento',
    ca: '16 (cota de malha, escudo)', hp: '11 (2d8+2)', velocidade: '9m',
    atributos: { for: 13, des: 12, con: 12, int: 10, sab: 11, car: 10 },
    sentidos: 'Percepção Passiva 12', idiomas: 'qualquer um (geralmente Comum)',
    cr: '1/8', pe: 25, tracos: [],
    acoes: ['Lança: +3 para acertar, alcance 1,5m/6m. Dano: 4 (1d6+1) perfurante (1d8+1 com duas mãos).'],
  },
  {
    nome: 'Batedor (Scout)', categoria: 'Humanoide',
    tipo: 'Humanoide médio (qualquer raça), qualquer alinhamento',
    ca: '13 (armadura de couro)', hp: '16 (3d8+3)', velocidade: '9m',
    atributos: { for: 11, des: 14, con: 12, int: 11, sab: 13, car: 11 },
    sentidos: 'Percepção Passiva 15', idiomas: 'qualquer um (geralmente Comum)',
    cr: '1/2', pe: 100,
    tracos: ['Sentidos Aguçados: perícia em Percepção, Sobrevivência e Furtividade.'],
    acoes: [
      'Múltiplos Ataques: dois ataques corpo a corpo ou à distância.',
      'Espada Curta: +4 para acertar, alcance 1,5m. Dano: 5 (1d6+2) perfurante.',
      'Arco Longo: +4 para acertar, alcance 45/180m. Dano: 6 (1d8+2) perfurante.',
    ],
  },
  {
    nome: 'Veterano', categoria: 'Humanoide',
    tipo: 'Humanoide médio (qualquer raça), qualquer alinhamento',
    ca: '17 (cota de placas)', hp: '58 (9d8+18)', velocidade: '9m',
    atributos: { for: 16, des: 13, con: 14, int: 10, sab: 11, car: 10 },
    sentidos: 'Percepção Passiva 12', idiomas: 'qualquer um (geralmente Comum)',
    cr: '3', pe: 700, tracos: [],
    acoes: [
      'Múltiplos Ataques: dois ataques com espada longa e (se tiver) um com adaga.',
      'Espada Longa: +5 para acertar, alcance 1,5m. Dano: 7 (1d8+3) corte.',
      'Besta Pesada: +3 para acertar, alcance 30/120m. Dano: 6 (1d10+1) perfurante.',
    ],
  },
  {
    nome: 'Berserker', categoria: 'Humanoide',
    tipo: 'Humanoide médio (qualquer raça), qualquer alinhamento caótico',
    ca: '13 (peles)', hp: '67 (9d8+27)', velocidade: '9m',
    atributos: { for: 16, des: 12, con: 17, int: 9, sab: 11, car: 9 },
    sentidos: 'Percepção Passiva 10', idiomas: 'qualquer um (geralmente Comum)',
    cr: '2', pe: 450,
    tracos: ['Fúria Insana: se começa o turno com menos da metade dos PV, tem vantagem em ataques corpo a corpo.'],
    acoes: ['Machado Grande: +5 para acertar, alcance 1,5m. Dano: 9 (1d12+3) corte.'],
  },
  {
    nome: 'Cultista', categoria: 'Humanoide',
    loot: { ouroFormula: '1d6+2', tabela: [{ item: null, peso: 45 }, { item: 'Amuleto de símbolo profano', peso: 25, qtd: 1 }, { item: 'Vela negra ritual', peso: 20, qtd: 1 }, { item: 'Bilhete cifrado do culto', peso: 10, qtd: 1 }] },
    tipo: 'Humanoide médio (qualquer raça), qualquer alinhamento não-bom',
    ca: '12 (armadura de couro)', hp: '9 (2d8)', velocidade: '9m',
    atributos: { for: 11, des: 12, con: 10, int: 10, sab: 11, car: 10 },
    sentidos: 'Percepção Passiva 10', idiomas: 'qualquer um (geralmente Comum)',
    cr: '1/8', pe: 25,
    tracos: ['Devoção Sombria: vantagem em salvaguardas contra amedrontar e enfeitiçar.'],
    acoes: ['Cimitarra: +3 para acertar, alcance 1,5m. Dano: 4 (1d6+1) corte.'],
  },
  {
    nome: 'Sacerdote (Priest)', categoria: 'Humanoide',
    tipo: 'Humanoide médio (qualquer raça), qualquer alinhamento',
    ca: '13 (camisão de malha)', hp: '27 (5d8+5)', velocidade: '7,5m',
    atributos: { for: 10, des: 10, con: 12, int: 13, sab: 16, car: 13 },
    sentidos: 'Percepção Passiva 13', idiomas: 'qualquer dois idiomas',
    cr: '2', pe: 450,
    tracos: ['Conjurador Divino (5º nível, SAB, CD 13). Truques: Chama Sagrada, Luz, Taumaturgia.'],
    acoes: ['Maça: +2 para acertar, alcance 1,5m. Dano: 3 (1d6) concussão.'],
    conjuracao: ['1º (4): Curar Ferimentos, Escudo da Fé. 2º (3): Arma Espiritual, Restauração Menor. 3º (2): Despertar o Mal, Dissipar Magia.'],
  },
  {
    nome: 'Mago (Mage)', categoria: 'Humanoide',
    tipo: 'Humanoide médio (qualquer raça), qualquer alinhamento',
    ca: '12 (15 com Armadura do Mago)', hp: '40 (9d8)', velocidade: '9m',
    atributos: { for: 9, des: 14, con: 11, int: 17, sab: 12, car: 11 },
    sentidos: 'Percepção Passiva 11', idiomas: 'qualquer quatro idiomas',
    cr: '6', pe: 2300,
    tracos: ['Conjurador Arcano (9º nível, INT, CD 14, +6 ataque). Truques: Raio de Fogo, Luz, Mão Mágica, Prestidigitação.'],
    acoes: ['Adaga: +5 para acertar, alcance 1,5m/6m. Dano: 4 (1d4+2) perfurante.'],
    conjuracao: [
      '1º (4): Detectar Magia, Armadura do Mago, Mísseis Mágicos, Escudo.',
      '2º (3): Visão no Escuro, Imagem Espelhada, Embaçar. 3º (3): Bola de Fogo, Contramágica, Voo.',
      '4º (3): Muralha de Fogo, Invisibilidade Maior. 5º (1): Cone de Frio.',
    ],
  },
  {
    nome: 'Orc', categoria: 'Humanoide',
    loot: { ouroFormula: '2d6+3', tabela: [{ item: null, peso: 50 }, { item: 'Machado grosseiro', peso: 20, qtd: 1 }, { item: 'Colar de presas', peso: 20, qtd: 1 }, { item: 'Estandarte de tribo rasgado', peso: 10, qtd: 1 }] },
    tipo: 'Humanoide médio (orc), caótico e mau',
    ca: '13 (armadura de couro)', hp: '15 (2d8+6)', velocidade: '9m',
    atributos: { for: 16, des: 12, con: 16, int: 7, sab: 11, car: 10 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 10', idiomas: 'Comum, Orc',
    cr: '1/2', pe: 100,
    tracos: ['Agressivo: como ação bônus, move-se até seu deslocamento na direção de um inimigo visível.'],
    acoes: [
      'Machado Grande: +5 para acertar, alcance 1,5m. Dano: 9 (1d12+3) corte.',
      'Azagaia: +5 para acertar, alcance 1,5m/9m. Dano: 6 (1d6+3) perfurante.',
    ],
  },
  {
    nome: 'Kobold', categoria: 'Humanoide',
    loot: { ouroFormula: '1d6', tabela: [{ item: null, peso: 60 }, { item: 'Pedrinha brilhante (sem valor)', peso: 20, qtd: 1 }, { item: 'Funda e pedras', peso: 12, qtd: 1 }, { item: 'Escama "da sorte" de dragão (falsa?)', peso: 8, qtd: 1 }] },
    tipo: 'Humanoide pequeno (kobold), leal e mau',
    ca: '12', hp: '5 (2d6-2)', velocidade: '9m',
    atributos: { for: 7, des: 15, con: 9, int: 8, sab: 7, car: 8 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 8', idiomas: 'Comum, Dracônico',
    cr: '1/8', pe: 25,
    tracos: ['Táticas de Matilha: vantagem em ataques se um aliado estiver a 1,5m do alvo.', 'Sensibilidade à Luz Solar: desvantagem sob luz solar.'],
    acoes: [
      'Adaga: +4 para acertar, alcance 1,5m/6m. Dano: 4 (1d4+2) perfurante.',
      'Funda: +4 para acertar, alcance 9/36m. Dano: 4 (1d4+2) concussão.',
    ],
  },
  {
    nome: 'Gnoll', categoria: 'Humanoide',
    tipo: 'Humanoide médio (gnoll), caótico e mau',
    ca: '15 (armadura de peles, escudo)', hp: '22 (5d8)', velocidade: '9m',
    atributos: { for: 14, des: 12, con: 11, int: 6, sab: 10, car: 7 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 10', idiomas: 'Gnoll',
    cr: '1/2', pe: 100,
    tracos: ['Investida Sanguinária: ao reduzir uma criatura a 0 PV, move-se até metade do deslocamento e ataca como ação bônus.'],
    acoes: [
      'Mordida: +4 para acertar, alcance 1,5m. Dano: 4 (1d4+2) perfurante.',
      'Lança: +4 para acertar, alcance 1,5m/9m. Dano: 5 (1d6+2) perfurante.',
      'Arco Longo: +3 para acertar, alcance 45/180m. Dano: 5 (1d8+1) perfurante.',
    ],
  },
  {
    nome: 'Mago Drow (Nezznar - chefe de Phandelver)', categoria: 'Humanoide',
    tipo: 'Humanoide médio (elfo), neutro e mau',
    ca: '12 (15 com Armadura Mágica)', hp: '49 (9d8+9)', velocidade: '9m',
    atributos: { for: 9, des: 14, con: 13, int: 17, sab: 12, car: 11 },
    sentidos: 'Visão no Escuro 36m, Percepção Passiva 11', idiomas: 'Comum, Élfico, Subcomum',
    cr: '6', pe: 2300,
    tracos: [
      'Sensibilidade ao Sol: desvantagem em ataques e Percepção visual à luz solar.',
      'Magia Inata (Drow): à vontade Luzes Dançantes; 1/dia cada Escuridão, Sugestão Mágica, Levitar.',
    ],
    acoes: ['Adaga: +4 para acertar, alcance 1,5m/6m. Dano: 4 (1d4+2) perfurante.'],
    conjuracao: [
      'Conjurador de 9º nível (CD 13, +5 ataque). Truques: Mãos Mágicas, Raio de Fogo, Luz.',
      '1º (4): Armadura Mágica, Escudo, Mísseis Mágicos. 3º (3): Bola de Fogo, Voo. 4º (3): Confusão. 5º (1): Cone de Frio.',
    ],
  },

  // ---------- ANIMAIS / FERAS ----------
  {
    nome: 'Lobo', categoria: 'Animal',
    loot: { ouroFormula: '0d1', tabela: [{ item: null, peso: 40 }, { item: 'Pele de lobo (2 po ao curtidor)', peso: 45, qtd: 1 }, { item: 'Presas de lobo', peso: 15, qtd: 2 }] },
    tipo: 'Animal médio, sem alinhamento',
    ca: '13', hp: '11 (2d8+2)', velocidade: '12m',
    atributos: { for: 12, des: 15, con: 12, int: 3, sab: 12, car: 6 },
    sentidos: 'Percepção Passiva 13', idiomas: '—', cr: '1/4', pe: 50,
    tracos: ['Audição e Olfato Aguçados.', 'Tático em Grupo: vantagem se um aliado estiver a 1,5m do alvo.'],
    acoes: ['Mordida: +4 para acertar, alcance 1,5m. Dano: 7 (2d4+2) perfurante. DT 11 Força ou cai prostrado.'],
  },
  {
    nome: 'Lobo Atroz (Dire Wolf)', categoria: 'Animal',
    tipo: 'Animal grande, sem alinhamento',
    ca: '14 (armadura natural)', hp: '37 (5d10+10)', velocidade: '15m',
    atributos: { for: 17, des: 15, con: 15, int: 3, sab: 12, car: 7 },
    sentidos: 'Percepção Passiva 13', idiomas: '—', cr: '1', pe: 200,
    tracos: ['Audição e Olfato Aguçados.', 'Tático em Grupo: vantagem se um aliado estiver a 1,5m do alvo.'],
    acoes: ['Mordida: +5 para acertar, alcance 1,5m. Dano: 10 (2d6+3) perfurante. DT 13 Força ou cai prostrado.'],
  },
  {
    nome: 'Urso-Pardo', categoria: 'Animal',
    tipo: 'Animal grande, sem alinhamento',
    ca: '11 (armadura natural)', hp: '34 (4d10+12)', velocidade: '12m, escalar 9m',
    atributos: { for: 19, des: 10, con: 16, int: 2, sab: 13, car: 7 },
    sentidos: 'Percepção Passiva 13', idiomas: '—', cr: '1', pe: 200,
    tracos: ['Olfato Aguçado.'],
    acoes: [
      'Múltiplos Ataques: uma mordida e uma garrada.',
      'Mordida: +6 para acertar, alcance 1,5m. Dano: 8 (1d8+4) perfurante.',
      'Garras: +6 para acertar, alcance 1,5m. Dano: 11 (2d6+4) cortante.',
    ],
  },
  {
    nome: 'Rato Gigante', categoria: 'Animal',
    tipo: 'Animal pequeno, sem alinhamento',
    ca: '12', hp: '7 (2d6)', velocidade: '9m',
    atributos: { for: 7, des: 15, con: 11, int: 2, sab: 10, car: 4 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 10', idiomas: '—', cr: '1/8', pe: 25,
    tracos: ['Olfato Aguçado.', 'Tático em Grupo: vantagem se um aliado estiver a 1,5m do alvo.'],
    acoes: ['Mordida: +4 para acertar, alcance 1,5m. Dano: 4 (1d4+2) perfurante.'],
  },
  {
    nome: 'Aranha Gigante', categoria: 'Monstruosidade',
    tipo: 'Monstruosidade grande, sem alinhamento',
    ca: '14', hp: '26 (4d10+4)', velocidade: '9m, escalar 9m',
    atributos: { for: 14, des: 16, con: 12, int: 2, sab: 11, car: 4 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 12 (16 com teia)', idiomas: '—', cr: '1', pe: 200,
    tracos: ['Escalador.', 'Sentido de Teia.', 'Andar na Teia.'],
    acoes: [
      'Mordida: +5 para acertar, alcance 1,5m. Dano: 7 (1d8+3) perfurante + 9 (2d8) veneno (DT 11 Con para metade; inconsciente se reduzir a 0).',
      'Atirar Teia (recarrega 5-6): alcance 9/18m. DT 12 Destreza ou fica preso (DT 12 para escapar).',
    ],
  },
  {
    nome: 'Ursaco (Owlbear)', categoria: 'Monstruosidade',
    tipo: 'Monstruosidade grande, sem alinhamento',
    ca: '13 (armadura natural)', hp: '59 (7d10+21)', velocidade: '12m',
    atributos: { for: 20, des: 12, con: 17, int: 3, sab: 12, car: 7 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 13', idiomas: '—', cr: '3', pe: 700,
    tracos: ['Olfato Aguçado.'],
    acoes: [
      'Múltiplos Ataques: uma mordida e uma garrada.',
      'Mordida: +7 para acertar, alcance 1,5m. Dano: 10 (1d10+5) perfurante.',
      'Garras: +7 para acertar, alcance 1,5m. Dano: 14 (2d8+5) cortante.',
    ],
  },

  // ---------- MORTOS-VIVOS ----------
  {
    nome: 'Zumbi', categoria: 'Morto-vivo',
    loot: { ouroFormula: '1d6-1', tabela: [{ item: null, peso: 70 }, { item: 'Anel oxidado (2 po)', peso: 15, qtd: 1 }, { item: 'Pertence pessoal da vítima (gancho de história)', peso: 15, qtd: 1 }] },
    tipo: 'Morto-vivo médio, neutro e mau',
    ca: '8', hp: '22 (3d8+9)', velocidade: '6m',
    atributos: { for: 13, des: 6, con: 16, int: 3, sab: 6, car: 5 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 8', idiomas: 'entende o que falava em vida, mas não fala',
    cr: '1/4', pe: 50,
    tracos: ['Fortidão de Morto-Vivo: se o dano não o reduzir a 0, faz DT Con (5+dano); se passar, fica com 1 PV.'],
    acoes: ['Lambada: +3 para acertar, alcance 1,5m. Dano: 4 (1d6+1) concussão.'],
  },
  {
    nome: 'Esqueleto', categoria: 'Morto-vivo',
    loot: { ouroFormula: '1d6-1', tabela: [{ item: null, peso: 65 }, { item: 'Espada antiga corroída', peso: 15, qtd: 1 }, { item: 'Broche de família esquecida (10 po)', peso: 12, qtd: 1 }, { item: 'Moedas de cunhagem antiga (colecionador paga o dobro)', peso: 8, qtd: 1 }] },
    tipo: 'Morto-vivo médio, leal e mau',
    ca: '13 (armadura de couro)', hp: '13 (2d8+4)', velocidade: '9m',
    atributos: { for: 10, des: 14, con: 15, int: 6, sab: 8, car: 5 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 9', idiomas: 'entende o que falava em vida, mas não fala',
    cr: '1/4', pe: 50,
    tracos: ['Vulnerável a dano de concussão.', 'Imune a veneno e à condição envenenado.'],
    acoes: [
      'Espada Curta: +4 para acertar, alcance 1,5m. Dano: 5 (1d6+2) perfurante.',
      'Arco Curto: +4 para acertar, alcance 24/96m. Dano: 5 (1d6+2) perfurante.',
    ],
  },
  {
    nome: 'Carniçal (Ghoul)', categoria: 'Morto-vivo',
    tipo: 'Morto-vivo médio, caótico e mau',
    ca: '12', hp: '22 (5d8)', velocidade: '9m',
    atributos: { for: 13, des: 15, con: 10, int: 7, sab: 10, car: 6 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 10', idiomas: 'Comum', cr: '1', pe: 200,
    tracos: ['Imune a veneno e à condição envenenado.'],
    acoes: [
      'Garras: +2 para acertar, alcance 1,5m. Dano: 9 (2d6+2) cortante. Não-mortos-vivos: DT 10 Con ou paralisado por 1 min.',
      'Mordida: +2 para acertar, alcance 1,5m. Dano: 4 (2d4) perfurante.',
    ],
  },
  {
    nome: 'Carniçal Voraz (Ghast)', categoria: 'Morto-vivo',
    tipo: 'Morto-vivo médio, caótico e mau',
    ca: '13', hp: '36 (8d8)', velocidade: '9m',
    atributos: { for: 16, des: 17, con: 10, int: 11, sab: 10, car: 8 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 10', idiomas: 'Comum', cr: '2', pe: 450,
    tracos: ['Fedor: criaturas a 1,5m fazem DT 10 Con ou ficam enjoadas.', 'Resistência a dano necrótico.', 'Imune a veneno e envenenado.'],
    acoes: [
      'Mordida: +3 para acertar, alcance 1,5m. Dano: 12 (2d8+3) perfurante.',
      'Garras: +5 para acertar, alcance 1,5m. Dano: 10 (2d6+3) cortante. DT 10 Con ou paralisado por 1 min.',
    ],
  },
  {
    nome: 'Espectro (Specter)', categoria: 'Morto-vivo',
    tipo: 'Morto-vivo médio, caótico e mau',
    ca: '12', hp: '22 (5d8)', velocidade: '0m, voo 15m (flutuação)',
    atributos: { for: 1, des: 14, con: 11, int: 10, sab: 10, car: 11 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 10', idiomas: 'entende o que falava em vida', cr: '1', pe: 200,
    tracos: ['Movimento Incorpóreo: atravessa objetos e criaturas como terreno difícil.', 'Sensibilidade à Luz Solar: desvantagem sob luz solar.', 'Resistências e imunidades de morto-vivo.'],
    acoes: ['Toque Mortal: +4 para acertar, alcance 1,5m. Dano: 10 (3d6) necrótico; reduz o máximo de PV do alvo.'],
  },
  {
    nome: 'Sombra (Shadow)', categoria: 'Morto-vivo',
    tipo: 'Morto-vivo médio, caótico e mau',
    ca: '12', hp: '16 (3d8+3)', velocidade: '12m',
    atributos: { for: 6, des: 14, con: 13, int: 6, sab: 10, car: 8 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 10', idiomas: '—', cr: '1/2', pe: 100,
    tracos: ['Furtividade Amorfa: esconde-se em escuridão como ação bônus.', 'Fraqueza à Luz Solar: desvantagem sob luz solar.'],
    acoes: ['Toque de Força: +4 para acertar, alcance 1,5m. Dano: 9 (2d6+2) necrótico; reduz a Força do alvo em 1d4 (morre se chegar a 0).'],
  },
  {
    nome: 'Wight', categoria: 'Morto-vivo',
    tipo: 'Morto-vivo médio, neutro e mau',
    ca: '14 (armadura de couro batido)', hp: '45 (6d8+18)', velocidade: '9m',
    atributos: { for: 15, des: 14, con: 16, int: 10, sab: 13, car: 15 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 13', idiomas: 'os que falava em vida', cr: '3', pe: 700,
    tracos: ['Sensibilidade à Luz Solar.', 'Resistências de morto-vivo.'],
    acoes: [
      'Múltiplos Ataques: dois ataques com espada longa ou arco.',
      'Espada Longa: +4 para acertar. Dano: 6 (1d8+2) corte.',
      'Dreno de Vida: +4 para acertar, alcance 1,5m. Dano: 5 (1d6+2) necrótico; reduz o máximo de PV. Quem morre vira zumbi sob controle do Wight.',
    ],
  },
  {
    nome: 'Múmia', categoria: 'Morto-vivo',
    tipo: 'Morto-vivo médio, leal e mau',
    ca: '11 (armadura natural)', hp: '58 (9d8+18)', velocidade: '6m',
    atributos: { for: 16, des: 8, con: 15, int: 6, sab: 10, car: 12 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 10', idiomas: 'os que falava em vida', cr: '3', pe: 700,
    tracos: ['Vulnerável a fogo.', 'Resistências e imunidades de morto-vivo.'],
    acoes: [
      'Múltiplos Ataques: um Olhar Aterrador e um soco.',
      'Soco Putrefato: +5 para acertar. Dano: 10 (2d6+3) concussão + 10 (3d6) necrótico; DT 12 Con ou contrai a Maldição da Múmia.',
      'Olhar Aterrador: DT 11 Sab ou amedrontado por 1 min (paralisado se falhar muito).',
    ],
  },
  {
    nome: 'Caveira Flamejante (Flameskull)', categoria: 'Morto-vivo',
    tipo: 'Morto-vivo pequeno, neutro e mau',
    ca: '13', hp: '40 (9d6+9)', velocidade: '0m, voo 12m (flutuação)',
    atributos: { for: 1, des: 17, con: 12, int: 16, sab: 11, car: 14 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 10', idiomas: 'os que falava em vida', cr: '4', pe: 1100,
    tracos: ['Resistência a concussão/perfurante/cortante de armas não mágicas.', 'Imune a fogo, veneno, necrótico.', 'Reanimação: se destruída, renasce em 1h com PV cheios (a não ser que dissipada com água benta/dissipar magia).'],
    acoes: [
      'Múltiplos Ataques: dois Raios de Fogo.',
      'Raio de Fogo: +5 para acertar, alcance 9m. Dano: 10 (3d6) fogo.',
    ],
    conjuracao: ['1/dia cada: Bola de Fogo. À vontade: Luz, Mãos Mágicas. 1x: Embaçar, Detectar Magia.'],
  },

  // ---------- GIGANTES ----------
  {
    nome: 'Ogro', categoria: 'Gigante',
    loot: { ouroFormula: '3d6+10', tabela: [{ item: null, peso: 45 }, { item: 'Saco com "brilhantes" (moedas e vidro)', peso: 25, qtd: 1 }, { item: 'Barril de hidromel meio cheio', peso: 15, qtd: 1 }, { item: 'Gema (50 po) engolida por engano', peso: 15, qtd: 1 }] },
    tipo: 'Gigante grande, caótico e mau',
    ca: '11 (armadura de peles)', hp: '59 (7d10+21)', velocidade: '12m',
    atributos: { for: 19, des: 8, con: 16, int: 5, sab: 7, car: 7 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 8', idiomas: 'Comum, Gigante', cr: '2', pe: 450,
    tracos: [],
    acoes: [
      'Clava Grande: +6 para acertar, alcance 1,5m. Dano: 13 (2d8+4) concussão.',
      'Azagaia: +6 para acertar, alcance 9/36m. Dano: 11 (2d6+4) perfurante.',
    ],
  },
  {
    nome: 'Trol (Troll)', categoria: 'Gigante',
    tipo: 'Gigante grande, caótico e mau',
    ca: '15 (armadura natural)', hp: '84 (8d10+40)', velocidade: '9m',
    atributos: { for: 18, des: 13, con: 20, int: 7, sab: 9, car: 7 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 12', idiomas: 'Gigante', cr: '5', pe: 1800,
    tracos: ['Regeneração: recupera 10 PV no início do turno (cessa se sofreu ácido ou fogo; morre se começar com 0 PV e não regenerar).', 'Olfato Aguçado.'],
    acoes: [
      'Múltiplos Ataques: uma mordida e duas garras.',
      'Mordida: +7 para acertar. Dano: 7 (1d6+4) perfurante.',
      'Garras: +7 para acertar. Dano: 11 (2d6+4) cortante.',
    ],
  },
  {
    nome: 'Gigante da Colina (Hill Giant)', categoria: 'Gigante',
    tipo: 'Gigante enorme, caótico e mau',
    ca: '13 (armadura natural)', hp: '105 (10d12+40)', velocidade: '12m',
    atributos: { for: 21, des: 8, con: 19, int: 5, sab: 9, car: 6 },
    sentidos: 'Percepção Passiva 12', idiomas: 'Gigante', cr: '5', pe: 1800, tracos: [],
    acoes: [
      'Múltiplos Ataques: dois ataques com clava grande.',
      'Clava Grande: +8 para acertar, alcance 3m. Dano: 18 (3d8+5) concussão.',
      'Pedra: +8 para acertar, alcance 18/72m. Dano: 21 (3d10+5) concussão.',
    ],
  },

  // ---------- MONSTRUOSIDADES ----------
  {
    nome: 'Estirge (Stirge)', categoria: 'Monstruosidade',
    tipo: 'Monstruosidade minúscula, sem alinhamento',
    ca: '14', hp: '2 (1d4)', velocidade: '4,5m, voo 12m',
    atributos: { for: 4, des: 16, con: 11, int: 2, sab: 8, car: 6 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 9', idiomas: '—', cr: '1/8', pe: 25, tracos: [],
    acoes: ['Probóscide: +5 para acertar, alcance 1,5m. Dano: 5 (1d4+3) perfurante; prende-se e drena 5 (1d4+3) por turno.'],
  },
  {
    nome: 'Worg', categoria: 'Monstruosidade',
    tipo: 'Monstruosidade grande, neutro e mau',
    ca: '13 (armadura natural)', hp: '26 (4d10+4)', velocidade: '15m',
    atributos: { for: 16, des: 13, con: 13, int: 7, sab: 11, car: 8 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 14', idiomas: 'Goblin, Worg', cr: '1/2', pe: 100,
    tracos: ['Audição e Olfato Aguçados.'],
    acoes: ['Mordida: +5 para acertar, alcance 1,5m. Dano: 10 (2d6+3) perfurante. DT 13 Força ou prostrado.'],
  },
  {
    nome: 'Harpia', categoria: 'Monstruosidade',
    tipo: 'Monstruosidade média, caótico e mau',
    ca: '11', hp: '38 (7d8+7)', velocidade: '6m, voo 12m',
    atributos: { for: 12, des: 13, con: 12, int: 7, sab: 10, car: 13 },
    sentidos: 'Percepção Passiva 10', idiomas: 'Comum', cr: '1', pe: 200, tracos: [],
    acoes: [
      'Múltiplos Ataques: duas garras.',
      'Garras: +3 para acertar, alcance 1,5m. Dano: 6 (2d4+1) cortante.',
      'Canção Encantadora: criaturas que ouvem fazem DT 11 Sab ou ficam enfeitiçadas, andando em direção à harpia.',
    ],
  },
  {
    nome: 'Grifo (Griffon)', categoria: 'Monstruosidade',
    tipo: 'Monstruosidade grande, sem alinhamento',
    ca: '12', hp: '59 (7d10+21)', velocidade: '9m, voo 24m',
    atributos: { for: 18, des: 15, con: 16, int: 2, sab: 13, car: 8 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 15', idiomas: '—', cr: '2', pe: 450,
    tracos: ['Visão Aguçada.'],
    acoes: [
      'Múltiplos Ataques: uma bicada e uma garrada.',
      'Bicada: +6 para acertar. Dano: 8 (1d8+4) perfurante.',
      'Garras: +6 para acertar. Dano: 11 (2d6+4) cortante.',
    ],
  },
  {
    nome: 'Mantícora', categoria: 'Monstruosidade',
    tipo: 'Monstruosidade grande, leal e mau',
    ca: '14 (armadura natural)', hp: '68 (8d10+24)', velocidade: '9m, voo 15m',
    atributos: { for: 17, des: 16, con: 17, int: 7, sab: 12, car: 8 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 11', idiomas: 'Comum', cr: '3', pe: 700,
    tracos: ['Espinhos de Cauda: 24 espinhos, recuperam ao descanso longo.'],
    acoes: [
      'Múltiplos Ataques: três ataques (mordida + 2 garras, ou 3 espinhos).',
      'Mordida: +5 para acertar. Dano: 7 (1d8+3) perfurante.',
      'Garras: +5 para acertar. Dano: 6 (1d6+3) cortante.',
      'Espinho de Cauda: +5 para acertar, alcance 30/60m. Dano: 7 (1d8+3) perfurante.',
    ],
  },
  {
    nome: 'Minotauro', categoria: 'Monstruosidade',
    tipo: 'Monstruosidade grande, caótico e mau',
    ca: '14 (armadura natural)', hp: '76 (9d10+27)', velocidade: '12m',
    atributos: { for: 18, des: 11, con: 16, int: 6, sab: 16, car: 9 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 17', idiomas: 'Abissal', cr: '3', pe: 700,
    tracos: ['Investida: se mover 3m e atacar com chifres, +9 (2d8) de dano e DT 14 Força ou empurrado 3m e prostrado.', 'Memória de Labirinto: nunca se perde.'],
    acoes: [
      'Machado Grande: +6 para acertar. Dano: 17 (2d12+4) cortante.',
      'Chifres: +6 para acertar. Dano: 13 (2d8+4) perfurante.',
    ],
  },
  {
    nome: 'Nothic', categoria: 'Aberração',
    tipo: 'Aberração média, neutro e mau',
    ca: '15 (armadura natural)', hp: '45 (6d8+18)', velocidade: '9m',
    atributos: { for: 12, des: 16, con: 17, int: 8, sab: 12, car: 8 },
    sentidos: 'Visão no Escuro 36m, Percepção Passiva 11', idiomas: 'Subcomum, telepatia 36m', cr: '2', pe: 450,
    tracos: ['Penetrar Pensamentos: aprende medos/segredos de um alvo (DT 12 Sab) e ganha vantagem em ataques contra ele.'],
    acoes: [
      'Garras: +5 para acertar. Dano: 7 (2d4+2) cortante + 7 (2d6) necrótico.',
      'Raio Decadente (recarrega 5-6): alcance 9m. DT 12 Con ou 10 (3d6) necrótico e -1d4 de Força.',
    ],
  },
  {
    nome: 'Espectador (Spectator)', categoria: 'Aberração',
    tipo: 'Aberração média, leal e neutro',
    ca: '15 (armadura natural)', hp: '39 (6d8+12)', velocidade: '0m, voo 9m (flutuação)',
    atributos: { for: 10, des: 14, con: 14, int: 13, sab: 14, car: 11 },
    sentidos: 'Visão Verdadeira 36m, Percepção Passiva 16', idiomas: 'Subcomum, Profundo', cr: '3', pe: 700,
    tracos: ['Magia Inata: Detectar Magia e Detectar Pensamentos à vontade.'],
    acoes: [
      'Mordida: +4 para acertar. Dano: 10 (2d8+1) perfurante.',
      'Raios Oculares (até 2/turno): Mordedura Mágica (ácido), Ferir, Confusão, Paralisia (DT 13).',
    ],
  },

  // ---------- LIMOS ----------
  {
    nome: 'Lodo Cinzento (Gray Ooze)', categoria: 'Limo',
    tipo: 'Limo médio, sem alinhamento',
    ca: '8', hp: '22 (3d8+9)', velocidade: '3m, escalar 3m',
    atributos: { for: 12, des: 6, con: 16, int: 1, sab: 6, car: 2 },
    sentidos: 'Visão às Cegas 18m (cego além disso), Percepção Passiva 8', idiomas: '—', cr: '1/2', pe: 100,
    tracos: ['Corrói Metal: dano em armas/armaduras de metal que o atingem ou são atingidas.', 'Falso Aspecto: imóvel, parece pedra molhada.', 'Resistente a ácido, frio e fogo.'],
    acoes: ['Pseudópode: +3 para acertar, alcance 1,5m. Dano: 4 (1d6+1) concussão + 7 (2d6) ácido (corrói armadura não mágica).'],
  },
  {
    nome: 'Cubo Gelatinoso', categoria: 'Limo',
    tipo: 'Limo grande, sem alinhamento',
    ca: '6', hp: '84 (8d10+40)', velocidade: '4,5m',
    atributos: { for: 14, des: 3, con: 20, int: 1, sab: 6, car: 1 },
    sentidos: 'Visão às Cegas 18m (cego além disso), Percepção Passiva 8', idiomas: '—', cr: '2', pe: 450,
    tracos: ['Transparente: difícil de perceber (DT 15 Percepção).', 'Engolfar: ao mover-se, engole criaturas no caminho (DT 12 Des).'],
    acoes: ['Pseudópode: +4 para acertar, alcance 1,5m. Dano: 10 (3d6) ácido.'],
  },

  // ---------- ELEMENTAIS / CONSTRUCTOS ----------
  {
    nome: 'Gárgula', categoria: 'Elemental',
    tipo: 'Elemental médio, caótico e mau',
    ca: '15 (armadura natural)', hp: '52 (7d8+21)', velocidade: '9m, voo 18m',
    atributos: { for: 15, des: 11, con: 16, int: 6, sab: 11, car: 7 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 10', idiomas: 'Terran', cr: '2', pe: 450,
    tracos: ['Falso Aspecto: imóvel, indistinguível de estátua.', 'Resistência a dano de armas não mágicas não-adamantinas.'],
    acoes: [
      'Múltiplos Ataques: uma mordida e uma garrada.',
      'Mordida: +4 para acertar. Dano: 5 (1d6+2) perfurante.',
      'Garras: +4 para acertar. Dano: 5 (1d6+2) cortante.',
    ],
  },
  {
    nome: 'Armadura Animada', categoria: 'Constructo',
    tipo: 'Constructo médio, sem alinhamento',
    ca: '18 (armadura natural)', hp: '33 (6d8+6)', velocidade: '7,5m',
    atributos: { for: 14, des: 11, con: 13, int: 1, sab: 3, car: 1 },
    sentidos: 'Visão às Cegas 18m (cego além disso), Percepção Passiva 6', idiomas: '—', cr: '1', pe: 200,
    tracos: ['Antimagia Suscetível: incapacitada em campo antimagia.', 'Falso Aspecto: imóvel, parece armadura comum.', 'Imune a veneno, psíquico e várias condições.'],
    acoes: [
      'Múltiplos Ataques: dois ataques de golpe.',
      'Golpe: +4 para acertar, alcance 1,5m. Dano: 5 (1d6+2) concussão.',
    ],
  },
  {
    nome: 'Diabrete (Imp)', categoria: 'Corruptor',
    tipo: 'Corruptor minúsculo (diabo, metamorfo), leal e mau',
    ca: '13', hp: '10 (3d4+3)', velocidade: '6m, voo 12m',
    atributos: { for: 6, des: 17, con: 13, int: 11, sab: 12, car: 14 },
    sentidos: 'Visão no Escuro 36m, Percepção Passiva 11', idiomas: 'Infernal, Comum', cr: '1', pe: 200,
    tracos: ['Metamorfose: vira rato, corvo, aranha ou javali.', 'Visão do Diabo.', 'Resistência a frio e a armas não mágicas (exceto prata); imune a fogo e veneno.', 'Magia Inata: à vontade Invisibilidade (a si).'],
    acoes: ['Ferrão (forma de diabrete): +5 para acertar, alcance 1,5m. Dano: 5 (1d4+3) perfurante + 10 (3d6) veneno (DT 11 Con para metade).'],
  },
  {
    nome: 'Cão Infernal (Hell Hound)', categoria: 'Corruptor',
    tipo: 'Corruptor médio (diabo), leal e mau',
    ca: '15 (armadura natural)', hp: '45 (7d8+14)', velocidade: '15m',
    atributos: { for: 17, des: 12, con: 14, int: 6, sab: 13, car: 6 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 15', idiomas: 'entende Infernal mas não fala', cr: '3', pe: 700,
    tracos: ['Audição e Olfato Aguçados.', 'Táticas de Matilha.', 'Imune a fogo.'],
    acoes: [
      'Mordida: +5 para acertar. Dano: 7 (1d8+3) perfurante + 7 (2d6) fogo.',
      'Sopro de Fogo (recarrega 5-6): cone de 4,5m. DT 12 Des, 21 (6d6) fogo (metade se passar).',
    ],
  },

  // ---------- FEY ----------
  {
    nome: 'Dríade', categoria: 'Fey',
    tipo: 'Feérico médio, neutro',
    ca: '11 (16 com Escudo de Carvalho)', hp: '22 (5d8)', velocidade: '9m',
    atributos: { for: 10, des: 12, con: 11, int: 14, sab: 15, car: 18 },
    sentidos: 'Visão no Escuro 18m, Percepção Passiva 12', idiomas: 'Élfico, Silvestre', cr: '1', pe: 200,
    tracos: ['Passo Arbóreo: teleporta-se entre árvores a 18m.', 'Magia Inata (CD 14): à vontade Druidismo; 1/dia Enredar, Enfeitiçar Pessoa, Caminhar nas Árvores.'],
    acoes: ['Clava: +2 para acertar. Dano: 2 (1d4) concussão.', 'Encanto Feérico: DT 14 Sab ou enfeitiçado por 1 dia.'],
  },

  // ---------- DRAGÕES ----------
  {
    nome: 'Dragão Vermelho Filhote (Wyrmling)', categoria: 'Dragão',
    tipo: 'Dragão médio, caótico e mau',
    ca: '17 (armadura natural)', hp: '75 (10d8+30)', velocidade: '9m, escalar 9m, voo 18m',
    atributos: { for: 19, des: 10, con: 17, int: 12, sab: 11, car: 15 },
    sentidos: 'Visão Cega 3m, Visão no Escuro 18m, Percepção Passiva 14', idiomas: 'Comum, Dracônico', cr: '4', pe: 1100,
    tracos: ['Imune a fogo.'],
    acoes: [
      'Mordida: +6 para acertar, alcance 1,5m. Dano: 9 (1d10+4) perfurante + 3 (1d6) fogo.',
      'Sopro de Fogo (recarrega 5-6): cone de 4,5m. DT 13 Des, 24 (7d6) fogo (metade se passar).',
    ],
  },
  {
    nome: 'Dragão Branco Filhote (Wyrmling)', categoria: 'Dragão',
    tipo: 'Dragão médio, caótico e mau',
    ca: '16 (armadura natural)', hp: '32 (5d8+10)', velocidade: '9m, escavar 4,5m, nadar 9m, voo 18m',
    atributos: { for: 14, des: 10, con: 14, int: 5, sab: 10, car: 11 },
    sentidos: 'Visão Cega 3m, Visão no Escuro 18m, Percepção Passiva 14', idiomas: 'Dracônico', cr: '2', pe: 450,
    tracos: ['Imune a frio.'],
    acoes: [
      'Mordida: +4 para acertar, alcance 1,5m. Dano: 7 (1d10+2) perfurante + 2 (1d4) frio.',
      'Sopro de Gelo (recarrega 5-6): cone de 4,5m. DT 12 Con, 22 (5d8) frio (metade se passar).',
    ],
  },
];

// =====================================================
// CATEGORIAS (tipos) presentes - derivadas para o filtro
// =====================================================
const CATEGORIAS_MONSTRO = [...new Set(MONSTROS.map(m => m.categoria))].sort();

// =====================================================
// AVENTURAS - encontros organizados por seção
// =====================================================
const AVENTURAS = [
  {
    nome: 'A Mina Perdida de Phandelver',
    niveis: '1–5',
    descricao: 'Aventura introdutória clássica de D&D 5e, dos arredores de Neverwinter até a Caverna do Eco das Ondas.',
    encontros: [
      {
        nivel: '1', area: 'Estrada Triboar / Esconderijo de Cragmaw',
        sugestao: 'Emboscada de 4 Goblins na estrada (carroça dos Lionshield). No covil: Goblins, Lobos e Klarg (Bugbear) com 2 Lobos guardando o cativo Sildar.',
        monstros: ['Goblin', 'Lobo', 'Bugbear', 'Goblin Mestre (Goblin Boss)'],
      },
      {
        nivel: '2', area: 'Phandalin / Covil dos Punhos Vermelhos (Redbrand)',
        sugestao: 'Bandidos e Capangas Punho Vermelho, um Lodo Cinzento na cisterna, e o Nothic na masmorra guardando os segredos do Glasstaff.',
        monstros: ['Bandido', 'Capanga (Thug)', 'Lodo Cinzento (Gray Ooze)', 'Nothic'],
      },
      {
        nivel: '3', area: 'Caverna do Eco das Ondas - túneis superiores',
        sugestao: 'Carniçais nas criptas, Esqueletos e Zumbis nos cruzamentos, Estirges em áreas úmidas.',
        monstros: ['Carniçal (Ghoul)', 'Esqueleto', 'Zumbi', 'Estirge (Stirge)'],
      },
      {
        nivel: '4', area: 'Eco das Ondas - Forja de Magia',
        sugestao: 'Aranhas Gigantes nas teias, o Ogro (Grol) na sala do triturador, Espectador flutuando perto da Forja.',
        monstros: ['Aranha Gigante', 'Ogro', 'Espectador (Spectator)'],
      },
      {
        nivel: '5', area: 'Eco das Ondas - confronto final',
        sugestao: 'Caveira Flamejante guardiã reanimada e o confronto com Nezznar, a Aranha Negra (mago drow), com goblins/bugbears remanescentes.',
        monstros: ['Caveira Flamejante (Flameskull)', 'Mago Drow (Nezznar - chefe de Phandelver)'],
      },
      {
        nivel: 'Opcional', area: 'Floresta de Neverwinter',
        sugestao: 'Ursaco territorial vagando pela floresta - encontro de alto risco.',
        monstros: ['Ursaco (Owlbear)'],
      },
    ],
  },
  {
    nome: 'Encontros por Ambiente (genérico)',
    niveis: '1–6',
    descricao: 'Tabelas rápidas para montar encontros aleatórios em qualquer campanha, agrupados por ambiente.',
    encontros: [
      {
        nivel: '1–3', area: 'Floresta / Selva',
        sugestao: 'Predadores e feras territoriais. Bom para viagens e emboscadas naturais.',
        monstros: ['Lobo', 'Lobo Atroz (Dire Wolf)', 'Urso-Pardo', 'Aranha Gigante', 'Worg', 'Dríade', 'Ursaco (Owlbear)'],
      },
      {
        nivel: '1–4', area: 'Masmorra / Cripta',
        sugestao: 'Mortos-vivos e horrores subterrâneos guardando tumbas e ruínas.',
        monstros: ['Esqueleto', 'Zumbi', 'Carniçal (Ghoul)', 'Carniçal Voraz (Ghast)', 'Espectro (Specter)', 'Sombra (Shadow)', 'Armadura Animada', 'Gárgula'],
      },
      {
        nivel: '1–3', area: 'Estrada / Cidade',
        sugestao: 'Salteadores, milícias e mercenários — encontros sociais ou de combate.',
        monstros: ['Bandido', 'Capanga (Thug)', 'Bandido Capitão', 'Guarda', 'Veterano', 'Cultista', 'Batedor (Scout)'],
      },
      {
        nivel: '2–4', area: 'Cavernas / Subterrâneo',
        sugestao: 'Humanoides hostis e limos espreitando nas profundezas.',
        monstros: ['Goblin', 'Kobold', 'Orc', 'Hobgoblin', 'Gnoll', 'Lodo Cinzento (Gray Ooze)', 'Cubo Gelatinoso', 'Diabrete (Imp)'],
      },
      {
        nivel: '4–6', area: 'Montanha / Covil de Chefe',
        sugestao: 'Ameaças maiores para grupos mais experientes — gigantes, dragões jovens e bestas voadoras.',
        monstros: ['Ogro', 'Trol (Troll)', 'Gigante da Colina (Hill Giant)', 'Mantícora', 'Grifo (Griffon)', 'Minotauro', 'Cão Infernal (Hell Hound)', 'Dragão Vermelho Filhote (Wyrmling)', 'Dragão Branco Filhote (Wyrmling)'],
      },
    ],
  },
];

// Compatibilidade com código anterior
const SUGESTOES_PHANDELVER = AVENTURAS[0].encontros;
